/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sodbeans_phonemic_tts_impl_CarbonSpeak */

#ifndef _Included_org_sodbeans_phonemic_tts_impl_CarbonSpeak
#define _Included_org_sodbeans_phonemic_tts_impl_CarbonSpeak
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sodbeans_phonemic_tts_impl_CarbonSpeak
 * Method:    speakNative
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_sodbeans_phonemic_tts_impl_CarbonSpeak_speakNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_sodbeans_phonemic_tts_impl_CarbonSpeak
 * Method:    speakBlockingNative
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_sodbeans_phonemic_tts_impl_CarbonSpeak_speakBlockingNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_sodbeans_phonemic_tts_impl_CarbonSpeak
 * Method:    stopNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_sodbeans_phonemic_tts_impl_CarbonSpeak_stopNative
  (JNIEnv *, jobject);

/*
 * Class:     org_sodbeans_phonemic_tts_impl_CarbonSpeak
 * Method:    pauseNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_sodbeans_phonemic_tts_impl_CarbonSpeak_pauseNative
  (JNIEnv *, jobject);

/*
 * Class:     org_sodbeans_phonemic_tts_impl_CarbonSpeak
 * Method:    resumeNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_sodbeans_phonemic_tts_impl_CarbonSpeak_resumeNative
  (JNIEnv *, jobject);

/*
 * Class:     org_sodbeans_phonemic_tts_impl_CarbonSpeak
 * Method:    isSpeakingNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_sodbeans_phonemic_tts_impl_CarbonSpeak_isSpeakingNative
  (JNIEnv *, jobject);

/*
 * Class:     org_sodbeans_phonemic_tts_impl_CarbonSpeak
 * Method:    setVoiceNative
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_sodbeans_phonemic_tts_impl_CarbonSpeak_setVoiceNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_sodbeans_phonemic_tts_impl_CarbonSpeak
 * Method:    setVolumeNative
 * Signature: (D)Z
 */
JNIEXPORT jboolean JNICALL Java_org_sodbeans_phonemic_tts_impl_CarbonSpeak_setVolumeNative
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_sodbeans_phonemic_tts_impl_CarbonSpeak
 * Method:    setSpeedNative
 * Signature: (D)Z
 */
JNIEXPORT jboolean JNICALL Java_org_sodbeans_phonemic_tts_impl_CarbonSpeak_setSpeedNative
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_sodbeans_phonemic_tts_impl_CarbonSpeak
 * Method:    setPitchNative
 * Signature: (D)Z
 */
JNIEXPORT jboolean JNICALL Java_org_sodbeans_phonemic_tts_impl_CarbonSpeak_setPitchNative
(JNIEnv *, jobject, jdouble);
	
/*
 * Class:     org_sodbeans_phonemic_tts_impl_CarbonSpeak
 * Method:    initializeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_sodbeans_phonemic_tts_impl_CarbonSpeak_initializeNative
  (JNIEnv *, jobject);

/*
 * Class:     org_sodbeans_phonemic_tts_impl_CarbonSpeak
 * Method:    reinitializeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_sodbeans_phonemic_tts_impl_CarbonSpeak_reinitializeNative
  (JNIEnv *, jobject);

/*
 * Class:     org_sodbeans_phonemic_tts_impl_CarbonSpeak
 * Method:    destroyNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_sodbeans_phonemic_tts_impl_CarbonSpeak_destroyNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
