/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sapi_TextToSpeech */

#ifndef _Included_org_sapi_TextToSpeech
#define _Included_org_sapi_TextToSpeech
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sapi_TextToSpeech
 * Method:    speakNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_sapi_TextToSpeech_speakNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_sapi_TextToSpeech
 * Method:    speakNative
 * Signature: (Ljava/lang/Boolean;)V
 */
JNIEXPORT jboolean JNICALL Java_org_sapi_TextToSpeech_isSpeaking
  (JNIEnv *, jobject);

/*
 * Class:     org_sapi_TextToSpeech
 * Method:    stopNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_sapi_TextToSpeech_stopNative
  (JNIEnv *, jobject);

/*
 * Class:     org_sapi_TextToSpeech
 * Method:    createTTSNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_sapi_TextToSpeech_createTTSNative
  (JNIEnv *, jobject);

/*
 * Class:     org_sapi_TextToSpeech
 * Method:    destroyTTSNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_sapi_TextToSpeech_destroyTTSNative
  (JNIEnv *, jobject);

/*
 * Class:     org_sapi_TextToSpeech
 * Method:    getVoicesNative
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT jstring JNICALL Java_org_sapi_TextToSpeech_getVoicesNative
	(JNIEnv *env, jobject obj);

/*
 * Class:     org_sapi_TextToSpeech
 * Method:    getTextToSpeechEngine
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT jstring JNICALL Java_org_sapi_TextToSpeech_getTextToSpeechEngine
	(JNIEnv *env,jobject obj);

/*
 * Class:     org_sapi_TextToSpeech
 * Method:    setVoiceNative
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT jboolean JNICALL Java_org_sapi_TextToSpeech_setTextToSpeechEngine
	(JNIEnv *env,jobject obj,jstring strInput);

/*
 * Class:     org_sapi_TextToSpeech
 * Method:    setVoiceNative
 * Signature: (Ljava/lang/Boolean;)V
 */
JNIEXPORT jboolean JNICALL Java_org_sapi_TextToSpeech_setVoiceNative
	(JNIEnv *env,jobject obj,jstring strInput);

/*
 * Class:     org_sapi_TextToSpeech
 * Method:    speakBlockNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_sapi_TextToSpeech_speakBlockNative
	(JNIEnv *env,jobject obj,jstring str);

/*
 * Class:     org_sapi_TextToSpeech
 * Method:    reinitializeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_sapi_TextToSpeech_reinitializeNative
	(JNIEnv *env,jobject obj);

/*
 * Class:     org_sapi_TextToSpeech
 * Method:    pauseNative
 * Signature: ()V
 */
JNIEXPORT jboolean JNICALL Java_org_sapi_TextToSpeech_pauseNative
	(JNIEnv *env,jobject obj);

/*
 * Class:     org_sapi_TextToSpeech
 * Method:    resumeNative
 * Signature: ()V
 */
JNIEXPORT jboolean JNICALL Java_org_sapi_TextToSpeech_resumeNative
	(JNIEnv *env,jobject obj);

/*
 * Class:     org_sapi_TextToSpeech
 * Method:    setRateNative
 * Signature: ()V
 */
JNIEXPORT jboolean JNICALL Java_org_sapi_TextToSpeech_setRateNative
	(JNIEnv *env,jobject obj, jlong rate);

/*
 * Class:     org_sapi_TextToSpeech
 * Method:    getRateNative
 * Signature: ()V
 */
JNIEXPORT jlong JNICALL Java_org_sapi_TextToSpeech_getRateNative
	(JNIEnv *env,jobject obj);

/*
 * Class:     org_sapi_TextToSpeech
 * Method:    setVolumeNative
 * Signature: ()V
 */
JNIEXPORT jboolean JNICALL Java_org_sapi_TextToSpeech_setVolumeNative
	(JNIEnv *env,jobject obj, jlong vol);

/*
 * Class:     org_sapi_TextToSpeech
 * Method:    getVolumeNative
 * Signature: ()V
 */
JNIEXPORT jlong JNICALL Java_org_sapi_TextToSpeech_getVolumeNative
	(JNIEnv *env,jobject obj);

#ifdef __cplusplus
}
#endif
#endif
